import { MakeLogicType, actions, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'
import { subscriptions } from 'kea-subscriptions'

import { lemonToast } from '@posthog/lemon-ui'

import { teamLogic } from 'scenes/teamLogic'
import { userLogic } from 'scenes/userLogic'

import { UserType } from '~/types'

import {
    mcpGatewayServersList,
    mcpGatewayServiceAccountsAccessCreate,
    mcpGatewayServiceAccountsList,
} from 'products/mcp_store/frontend/generated/api'
import type {
    MCPGatewayServerApi,
    MCPServiceAccountApi,
    MCPServiceAccountServerApi,
} from 'products/mcp_store/frontend/generated/api.schemas'

function errorDetail(error: unknown): string | null {
    if (typeof error !== 'object' || error === null || !('detail' in error)) {
        return null
    }
    return typeof error.detail === 'string' ? error.detail : null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scoutMcpServersLogicValues {
    currentTeamId: number | null // teamLogic
    user: UserType | null // userLogic
    connectedGatewayServers: MCPGatewayServerApi[]
    currentUserId: number | null
    gatewayServers: MCPGatewayServerApi[]
    gatewayServersLoading: boolean
    scoutAccount: MCPServiceAccountApi | null
    scoutServers: MCPServiceAccountServerApi[]
    scoutServersLoading: boolean
    scoutSharedServerIds: Set<string>
    serverShareLoadingIds: Set<string>
    serviceAccounts: MCPServiceAccountApi[]
    serviceAccountsLoading: boolean
    teammateScoutServers: MCPServiceAccountServerApi[]
    yourScoutServers: MCPServiceAccountServerApi[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scoutMcpServersLogicActions {
    loadGatewayServers: () => any
    loadGatewayServersFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadGatewayServersSuccess: (
        gatewayServers: MCPGatewayServerApi[],
        payload?: any
    ) => {
        gatewayServers: MCPGatewayServerApi[]
        payload?: any
    }
    loadServiceAccounts: () => any
    loadServiceAccountsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadServiceAccountsSuccess: (
        serviceAccounts: MCPServiceAccountApi[],
        payload?: any
    ) => {
        serviceAccounts: MCPServiceAccountApi[]
        payload?: any
    }
    setScoutServerShared: (
        serverId: string,
        enabled: boolean
    ) => {
        enabled: boolean
        serverId: string
    }
    setScoutServerSharedComplete: (serverId: string) => {
        serverId: string
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scoutMcpServersLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        currentUserId: (user: UserType | null) => number | null
        scoutAccount: (serviceAccounts: MCPServiceAccountApi[]) => MCPServiceAccountApi | null
        scoutServers: (scoutAccount: MCPServiceAccountApi | null) => MCPServiceAccountServerApi[]
        yourScoutServers: (
            scoutServers: MCPServiceAccountServerApi[],
            currentUserId: number | null
        ) => MCPServiceAccountServerApi[]
        teammateScoutServers: (
            scoutServers: MCPServiceAccountServerApi[],
            currentUserId: number | null
        ) => MCPServiceAccountServerApi[]
        connectedGatewayServers: (gatewayServers: MCPGatewayServerApi[]) => MCPGatewayServerApi[]
        scoutSharedServerIds: (yourScoutServers: MCPServiceAccountServerApi[]) => Set<string>
        scoutServersLoading: (serviceAccountsLoading: boolean) => boolean
    }
}

export type scoutMcpServersLogicType = MakeLogicType<
    scoutMcpServersLogicValues,
    scoutMcpServersLogicActions,
    Record<string, any>,
    scoutMcpServersLogicMeta
>

export const scoutMcpServersLogic = kea<scoutMcpServersLogicType>([
    path(['scenes', 'inbox', 'logics', 'scoutMcpServersLogic']),
    connect({
        values: [teamLogic, ['currentTeamId'], userLogic, ['user']],
    }),
    actions({
        setScoutServerShared: (serverId: string, enabled: boolean) => ({ serverId, enabled }),
        setScoutServerSharedComplete: (serverId: string) => ({ serverId }),
    }),
    loaders(({ values }) => ({
        serviceAccounts: [
            [] as MCPServiceAccountApi[],
            {
                loadServiceAccounts: async () => {
                    if (values.currentTeamId === null) {
                        return []
                    }
                    const response = await mcpGatewayServiceAccountsList(String(values.currentTeamId), { limit: 500 })
                    return response.results
                },
            },
        ],
        gatewayServers: [
            [] as MCPGatewayServerApi[],
            {
                loadGatewayServers: async () => {
                    if (values.currentTeamId === null) {
                        return []
                    }
                    const response = await mcpGatewayServersList(String(values.currentTeamId), { limit: 500 })
                    return response.results
                },
            },
        ],
    })),
    reducers({
        serverShareLoadingIds: [
            new Set<string>(),
            {
                setScoutServerShared: (state, { serverId }) => new Set(state).add(serverId),
                setScoutServerSharedComplete: (state, { serverId }) => {
                    const next = new Set(state)
                    next.delete(serverId)
                    return next
                },
            },
        ],
    }),
    selectors({
        currentUserId: [(s) => [s.user], (user: UserType | null): number | null => user?.id ?? null],
        scoutAccount: [
            (s) => [s.serviceAccounts],
            (serviceAccounts: MCPServiceAccountApi[]): MCPServiceAccountApi | null =>
                serviceAccounts.find((account) => account.agent_key === 'scout') ?? null,
        ],
        scoutServers: [
            (s) => [s.scoutAccount],
            (scoutAccount: MCPServiceAccountApi | null): MCPServiceAccountServerApi[] => [
                ...(scoutAccount?.servers ?? []),
            ],
        ],
        // A grant belongs to one member. A scout run mounts the grants of the person it runs for
        // plus every team-scoped grant in the project, so a teammate's personal grant never backs
        // the viewer's scouts but a teammate's team share does. While the user is still loading
        // neither partition can be attributed, so both stay empty rather than reading the
        // viewer's own grants as teammates'.
        yourScoutServers: [
            (s) => [s.scoutServers, s.currentUserId],
            (scoutServers: MCPServiceAccountServerApi[], currentUserId: number | null): MCPServiceAccountServerApi[] =>
                currentUserId === null ? [] : scoutServers.filter((server) => server.shared_by.id === currentUserId),
        ],
        teammateScoutServers: [
            (s) => [s.scoutServers, s.currentUserId],
            (scoutServers: MCPServiceAccountServerApi[], currentUserId: number | null): MCPServiceAccountServerApi[] =>
                currentUserId === null
                    ? []
                    : scoutServers.filter((server) => server.shared_by.id !== currentUserId && server.scope === 'team'),
        ],
        connectedGatewayServers: [
            (s) => [s.gatewayServers],
            (gatewayServers: MCPGatewayServerApi[]): MCPGatewayServerApi[] =>
                gatewayServers
                    .filter((server) => server.your_connection !== null)
                    .sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' })),
        ],
        scoutSharedServerIds: [
            (s) => [s.yourScoutServers],
            (yourScoutServers: MCPServiceAccountServerApi[]): Set<string> =>
                new Set(yourScoutServers.map((server) => server.id)),
        ],
        scoutServersLoading: [
            (s) => [s.serviceAccountsLoading],
            (serviceAccountsLoading: boolean): boolean => serviceAccountsLoading,
        ],
    }),
    listeners(({ actions, values }) => ({
        setScoutServerShared: async ({ serverId, enabled }) => {
            const scoutAccount = values.scoutAccount
            const serverName = values.gatewayServers.find((server) => server.id === serverId)?.name ?? 'server'
            if (values.currentTeamId === null || scoutAccount === null) {
                actions.setScoutServerSharedComplete(serverId)
                return
            }
            // `scope` goes on every call because the endpoint defaults an omitted scope back to
            // personal, which would silently demote a team share on any re-share.
            const scope = values.yourScoutServers.find((grant) => grant.id === serverId)?.scope ?? 'personal'
            try {
                // The response carries the scout account's grants after the change, including who
                // backs each one, which a local merge cannot reconstruct.
                const updatedAccount = await mcpGatewayServiceAccountsAccessCreate(
                    String(values.currentTeamId),
                    scoutAccount.id,
                    { gateway_server_id: serverId, enabled, scope }
                )
                actions.loadServiceAccountsSuccess(
                    values.serviceAccounts.map((account) => (account.id === scoutAccount.id ? updatedAccount : account))
                )
                lemonToast[enabled ? 'success' : 'info'](
                    enabled
                        ? `Your scouts can now use ${serverName}`
                        : `${serverName} is no longer shared with your scouts`
                )
            } catch (error: unknown) {
                lemonToast.error(errorDetail(error) ?? `Could not update ${serverName} access for your scouts`)
            } finally {
                actions.setScoutServerSharedComplete(serverId)
            }
        },
    })),
    subscriptions(({ actions }) => ({
        currentTeamId: () => {
            actions.loadServiceAccounts()
            actions.loadGatewayServers()
        },
    })),
])
