# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from typing import Literal

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config


@config.config
class CloverAuthTypeConfig(config.Config):
    selection: Literal["api_token", "oauth"] = "api_token"
    api_token: str | None = None
    client_id: str | None = None
    refresh_token: str | None = None


@config.config
class CloverSourceConfig(config.Config):
    merchant_id: str
    auth_type: CloverAuthTypeConfig
    region: Literal["na", "eu", "latam", "sandbox"] = config.value(default="na")
