# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from typing import Literal

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config


@config.config
class DisplayVideo360AuthTypeConfig(config.Config):
    selection: Literal["service_account", "oauth"] = "service_account"
    service_account_key: str | None = None
    client_id: str | None = None
    client_secret: str | None = None
    refresh_token: str | None = None


@config.config
class DisplayVideo360SourceConfig(config.Config):
    auth_type: DisplayVideo360AuthTypeConfig
    partner_id: str
    advertiser_ids: str | None = None
