# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from typing import Literal

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config


@config.config
class GoogleDriveAuthMethodConfig(config.Config):
    selection: Literal["service_account", "oauth"] = "service_account"
    service_account_key: str | None = None
    impersonated_user_email: str | None = None
    client_id: str | None = None
    client_secret: str | None = None
    refresh_token: str | None = None


@config.config
class GoogleDriveSourceConfig(config.Config):
    auth_method: GoogleDriveAuthMethodConfig
    drive_id: str | None = None
