# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from typing import Literal

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config


@config.config
class MercadoPagoAuthMethodConfig(config.Config):
    selection: Literal["access_token", "oauth"] = "access_token"
    access_token: str | None = None
    client_id: str | None = None
    client_secret: str | None = None
    refresh_token: str | None = None


@config.config
class MercadoPagoSourceConfig(config.Config):
    auth_method: MercadoPagoAuthMethodConfig
